In [1]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 5
Enter the next value 7
Enter the next value 6
Enter the next value 5
Enter the next value 4
Enter the next value 3


array('i', [7, 6, 5, 4, 3])


In [2]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 5
Enter the next value 9
Enter the next value 8
Enter the next value 0
Enter the next value 5
Enter the next value 4


array('i', [9, 8, 0, 5, 4])


### Way of creating array using numpy

In [5]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [6]:
print(arr.dtype)

int64


In [7]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [8]:
print(arr.dtype)

float64


In [9]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [10]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [11]:
import numpy as np

In [12]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [13]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [14]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [15]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [17]:
import tkinter as tk
# Function to be called when the button is clicked
def on_button_click():
    label.config(text="Button clicked!")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Hello, Tkinter!")
label.pack(pady=20)

# Create a button widget
button = tk.Button(root, text="Click Me", command=on_button_click)
button.pack(pady=20)

# Run the application
root.mainloop()

In [18]:
import tkinter as tk
from tkinter import messagebox

# Function to be called when the button is clicked
def on_button_click():
    user_input = entry.get()
    messagebox.showinfo("Information", f"You entered: {user_input}")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Enter something:")
label.pack(pady=10)

# Create a text entry widget
entry = tk.Entry(root, width=30)
entry.pack(pady=10)

# Create a button widget
button = tk.Button(root, text="Submit", command=on_button_click)
button.pack(pady=10)

# Run the appication
root.mainloop()
